### ISSUE TITLE
你好,请问一下用你这个库支持用A4纸打印图片吗?

### ISSUE THREAD

**Issue by yolanda0628** [AlexMofer/Printer#4]

**Comment by AlexMofer** [comment]
理论上是支持的，但是我没有实际测试过，建议使用这个Dome：[https://play.google.com/store/apps/details?id=am.project.x](https://play.google.com/store/apps/details?id=am.project.x)，用IP+端口的模式测试一下。能够打印就没问题，排版上的问题就是可调节的。

**Comment by yolanda0628** [comment]
是不是要去实现PrinterWriter这个抽象类,实现A4纸的纸宽么?   还有就是用你说的哪个demo的话是调用安装改apk进行打印么?谢谢!!

**Comment by AlexMofer** [comment]
对的，要完美匹配的话要实现PrinterWriter的，我那个demo只是个样例，你可以下载安装测试是否能打印。附两张截图

2017年3月10日 13:54，"pbq" <notifications@github.com>写道：

是不是要去实现PrinterWriter这个抽象类,实现A4纸的纸宽么? 还有就是用你说的哪个demo的话是调用安装改apk进行打印么?谢谢!!

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/AlexMofer/Printer/issues/4#issuecomment-285584933>, or mute
the thread
